### PR TITLE
Email page client component

### PR DESCRIPTION
**Pull request by matviikotolyk**
## Description

EmailForm component to push down 'use client' down the root tree

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

Checkout the branch `matviikotolyk/email-form` and start the local server

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Comment by ucey-star** [comment]
This branch fails the deployment check from Vercel. It reads:

Type error: Property 'startupName' is missing in type 'CardData' but required in type 'ExploreMoreData'.

**Comment by ucey-star** [comment]
Great work on isolating the client-side logic into the EmailForm component. This really helps maintain separation of concerns and adheres to best practices!

**Review by ucey-star — CHANGES_REQUESTED** [review]
This branch fails the deployment check from Vercel. It reads:

Type error: Property 'startupName' is missing in type 'CardData' but required in type 'ExploreMoreData'.

**Comment by ucey-star** [comment]
Consider: Adding a screenshot just to ensure that you tested the new component and everything works as expected

**Comment by matviikotolyk** [comment]
this was a prop error on the exploreMore component. pushed a fix for this and the lint warnings across the app @ucey-star

**Comment by ucey-star** [comment]
I fixed the code quality check for this commit

**Review by ucey-star — APPROVED** [review]

**Pull request merged**
