### PR TITLE
Added a page for verification code based on "Verification Code" page in V2 Designs

### PR DESCRIPTION
**Pull request by avalucianelson**
## Description

This PR develops the "Verification Code" page from the most recent [(V2) Designs.](https://www.figma.com/design/vnyb5qwvnjpDVaO7rOC3ZL/ID8-High-Fidelity-Designs?node-id=353-306&node-type=frame&t=TkIi7i5QECv17J0S-0). This PR: 

- 	**Created a New Verification Code Page:** Developed a new page.tsx file in the verify directory to handle the verification code input process as part of the user authentication flow.
- 	**Integrated ID8's Official Logo:** Replaced a generic icon with the actual project’s ID8_logo.svg, enhancing brand consistency and visual appeal on the verification page. The logo can be found in the public directory, stored as ID8_logo.svg.
- 	**Utilized Material-UI Components:** Implemented the verification page using Material-UI components like Container, Typography, TextField, and Button to maintain a consistent look and feel with the rest of the application.
- 	**Styling Consistency:** Ensured that the page styling matches the existing pages by using consistent background gradients and text styling.
- 	**Responsive Design Setup:** Configured the layout to be responsive, ensuring that it adjusts well to various screen sizes for accessibility and usability.
- 	**Copywriting Adjustments:** In an effort to increase clarify for the user, I adjusted copywriting from the designs. Specifically, I changed the main text ("We have sent you a verification code") to include an exclamation point (it is a complete sentence and was missing punctuation, so I felt this change was necessary). I changed the button text from "Verify Code" to "Verify" as I felt that was more clear. 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

To verify the changes, navigate to http://localhost:3000/verify.

### Implemented Verification Page:
image

### Verification Page in V2 Designs:
image

### CODE REVIEW

**Comment by katyaivaniuk** [comment]
@avalucianelson  Great job on setting up the verification page—it looks visually cohesive with the V2 designs! The structure of the component is easy to follow, which makes it really readable for people who are not writing the code 😊

It might be helpful to add some basic validation for the input field, like a message to prompt the user if they try to submit without entering a code. This could improve the user experience by guiding them through the process more smoothly.

Overall, awesome work on the page styling and layout!

**Comment by ucey-star** [comment]
Also I apologize for the failing check " Assign Random Reviewer / assign-reviewer (pull_request) " that is totally on me. I will look into it and try to fix it or just remove it entirely.

**Comment by avalucianelson** [comment]
Hey guys -- our V2 designs (based on pivoting to Capstones and after reviewing feasibility of using verification codes) no longer seem to include this feature. Should this PR be closed?

**Comment by FlaIespa** [comment]
> Hey guys -- our V2 designs (based on pivoting to Capstones and after reviewing feasibility of using verification codes) no longer seem to include this feature. Should this PR be closed?

Hey, @avalucianelson. Yes! Given that we are not using this feature anymore, I am going to close this PR.

**Pull request closed without merging**
