### PR TITLE
Adding GA4 and Hotjar Tracking 

### PR DESCRIPTION
**Pull request by avalucianelson**
## Description

This PR implements tracking for Google Analytics and Hotjar for ID8. The Google Analytics tracking code has been added to monitor user interactions and page views, while the Hotjar tracking code allows for heatmaps and session recordings to better understand user behavior. These changes will help improve our analytics capabilities and provide insights into user engagement.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

To verify the changes:
1. Run the application locally using npm run dev.
2. Open the application in your browser and navigate through different pages.
3. Check the console for any errors related to the Google Analytics or Hotjar scripts.
4. Use the Google Tag Assistant extension to confirm that the Google Analytics tag is firing correctly.
5. Verify that the Hotjar script is loading by checking the network requests in the Developer Tools.

You can also check the Real-Time reports in the Google Analytics and Hotjar dashboards to ensure that data is being tracked correctly. Please let me know if you do not have access to the GA dashboard (everybody should already have access) and if you'd like me to share access to Hotjar (will need to check if doing so is possible with the free plan). 

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Review by matviikotolyk — COMMENTED** [review]
Looks great @avalucianelson !

Just two things: 
- let's move the IDs to the .env file as environment variables for security and refer to them here.
- it looks like it's helpful to include the strategy="afterInteractive" prop in the google <Script /> component (The strategy="afterInteractive" attribute indicates that the script should load after the page becomes interactive, which helps with the performance of your site. from here https://www.dhiwise.com/post/integrating-nextjs-google-analytics-a-step-by-step-guide)

**Comment by avalucianelson** [comment]
Thanks so much for the feedback, @matviikotolyk! When I used the strategy="afterInteractive" prop I got an error so I switched to strategy="lazyOnload". I can revisit it! I'll message u on telegram as I try to figure that out if I can't do so. I'll also move the IDs to the .env file and refer to them as variables asap :) thanks so much for your input and expertise.

**Comment by ucey-star** [comment]
Re ran the assign-reviewer job! Now it passes

**Comment by matviikotolyk** [comment]
@avalucianelson sounds great! I think I only saw the strategy prop included for the Hotjar tracking code; shouldn't be a biggy in any case.

**Comment by avalucianelson** [comment]
Okay ya @matviikotolyk -- I went ahead and updated so they are variables. I played around with the strategy props just a bit and was still running into issues doing it any other way. In my opinion, I think it might be best to merge this as is for now and then revisit the strategy props later. Just so we can start funneling data without delay. Let me know what you think and ofc feel free to look into the strategy prop stuff too. Tysm!

**Comment by matviikotolyk** [comment]
sounds good to me! The only thing to confirm with @lewiskyron is whether we store the environment variables in the Vercel deployment (there's a way to add them there so that they are available in prod)

**Review by matviikotolyk — APPROVED** [review]
The environment variables are to be added in the Vercel deployment - otherwise, everything looks good!

**Pull request merged**
