### PR TITLE
Add navbar to home page

### PR DESCRIPTION
**Pull request by ucey-star**
## Description

Add NavBar component to home page

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

1. Go to the /home page.
2. Verify that the navigation bar matches the expected design as shown in the Figma prototype.
3. Navigate to other pages, then return to the home page. Ensure that clicking "Home" redirects you back to the /home page correctly.

## Screenshots (if applicable)

image

### CODE REVIEW

**Review by Mykhailo-Chudyk — APPROVED** [review]
Should be good now!

**Comment by lewiskyron** [comment]
@mchudyk The navbar should be suspended at the top always. This provides for easy navigation so that users do not have to scroll all the way up to access the icons there. Currently, this is not implemented. I believe Ucey's branch had the navbar added to the home page. If it is fine with you can we close this branch and open another PR with the new updates code in main. This would also completely allow us to ignore the merge conflict.

**Comment by Mykhailo-Chudyk** [comment]
@lewiskyron Agreed! Closing this PR and the relevant issue.

**Comment by Mykhailo-Chudyk** [comment]
@lewiskyron Agreed! Closing this PR and the relevant issue.

**Pull request closed without merging**
