### PR TITLE
Created and added Edit Project page

### PR DESCRIPTION
**Pull request by nnnour**
## Description

This PR introduces a new Edit Project page, fully implementing the design mockups provided. The page includes:

- An Edit Project form section with inputs for project details such as:
      -       Project name
      -       Description (limited to 150 characters)
      -       Project link
      -       Demo link
      -       Product description
      -       User questions
      -       File upload section
      -       Multi-select tags field
- A Feedback section that includes:
      - Statistics for views, comments, and likes using icons
      - List of feedback comments with user name, feedback, and date
      - A text input field for adding new comments

This page follows the design guidelines and includes reusable components (e.g., GradientButton, Navbar...) for consistency with the rest of the application.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

1. Run the app locally using npm run dev or yarn dev.
2. Navigate to the Edit Project page (/edit_project).
3. Verify that all form fields are displayed correctly

## Screenshots (if applicable)

If your changes include visual components, add screenshots showing the affected pages or elements.
editproject

### CODE REVIEW

**Comment by matviikotolyk** [comment]
@nnnour nice job! This seems like a very big file - can you modularize it a bit so that there are a few components used inside of the page component? Also, the mock data is helpful for reviewing the frontend but may be redundant when we are implementing the backend so perhaps it's best to leave those empty and use empty objects to simulate what a connection to the backend will look like.

**Comment by lewiskyron** [comment]
Nice job! I am trying to understand how this page would be integrated into the entire application. For this to be added to the app we would need a `my projects` button added to the navbar where users can access all their projects so that when they click a particular project they see this page(`editProject Page`). Can we please have these additions? If this additions are not to be done by you can you please write in the PR description who will work on this additional pages to ensure we have and end to end UI experience

**Review by FlaIespa — COMMENTED** [review]
Hey, Nour! Thank you for your work here! 
Recently, the multiple project functionality has been merged. There, users have the ability to edit their project (which was a previous functionality already implemented in project_idea) add more than one project (which did require a new component that didn't fetch previous information of already submitted projects, but it provided a clear form). The reason I adding this in this comment, is that you might want to consider taking a look at the current version of the app in main (or the deployed version) and checking if there is still a need to continuing working on this PR. I might be missing something, so do let me know!

**Comment by lewiskyron** [comment]
Closing this as this page has already been implemented and merged into main.

**Pull request closed without merging**
