### PR TITLE
Updated auth pages and a hook for determining if the screen is mobile

### PR DESCRIPTION
**Pull request by matviikotolyk**
## Description

Simple changes to the styling of the auth pages and a useMobile hook to adjust the styling when Material's useMediaQuery is not available to use.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Tests (adding or updating tests)
- [ ] Documentation update

## Testing Instructions

checkout the `matviikotolyk/auth-pages-improve` branch and start the development server. Note, this is a very small update

## Screenshots (if applicable)

If your changes include visual components, add screenshots showing the affected pages or elements.

### CODE REVIEW

**Comment by lewiskyron** [comment]
Hi Matvii this look good to me. Thanks you for adding the mobile hook. There are a few conflicts here can we resolve them together since I am also working on this same pages. Would like to have this merged as soon as possible.

**Comment by matviikotolyk** [comment]
@lewiskyron just resolved the conflicts. Just need your approval to merge

**Comment by matviikotolyk** [comment]
@lewiskyron can you please approve this when you get a minute?

**Comment by ucey-star** [comment]
Please ensure that this branch has latest changes in the main (the one you added)

**Review by lewiskyron — APPROVED** [review]

**Pull request merged**
